import type { Metadata } from "next";
import {
  ColorSchemeScript,
  mantineHtmlProps,
  MantineProvider,
} from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { HeaderComponent } from "@/components/common/HeaderComponent";
import { ApiProvider } from "@/provider/ApiProvider";
import { AuthProvider } from "@/provider/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider>
          <Notifications />
          <ApiProvider>
            <AuthProvider>
              <HeaderComponent />
              <div className="flex justify-center">
                <div className="max-w-[95%] min-w-[300px]">
                  <div className="flex justify-start w-[100%] ml-3 mb-4">
                    <div>{children}</div>
                  </div>
                </div>
              </div>
            </AuthProvider>
          </ApiProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
