import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { HeaderComponent } from "@/components/common/HeaderComponent";
import { ToastComponent } from "@/components/common/ToastComponent";
import ApiProvider from "@/provider/ApiProvider";
import AuthProvider from "@/provider/AuthProvider";
import StoreProvider from "@/provider/StoreProvider";
import "@/style/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <ApiProvider>
            <AuthProvider>
              <HeaderComponent />
              <ToastComponent />
              <div className="flex justify-center mt-3">
                <div className="max-w-[98%] min-w-[300px]">
                  <div className="flex justify-start w-[100%] ml-3 mb-4">
                    <div>{children}</div>
                  </div>
                </div>
              </div>
            </AuthProvider>
          </ApiProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
